### ISSUE TITLE
Allow users to toggle different words-per-minute animation settings

### ISSUE THREAD

**Issue by frederickobrien** [gonzo-engineering/teeline-online#137]
Following on from the groundwork laid in #134, it would be lovely to give users control over what speed outlines are 'written' at. Being able to see the difference between 60 and 120 would be very instructive - especially if we start rendering full sentences/passages (#136)

**Comment by mxdvl** [comment]
With #174 the length of each glyph is known, so you could estimate a drawing speed that would achieve a WPM count by processing a sample:

1. get 100 common words
2. disemvowled the text
3. convert to outlines
4. measure the total length
5. draw one sixtieth of that length per second!
