### ISSUE TITLE
Generator Input Field Unresponsive on Firefox

### ISSUE THREAD

**Issue by sappho7124** [gonzo-engineering/teeline-online#386]
The generator input field does not work on Firefox. While it functions correctly on Chrome and Edge, where clicking the field allows text input, on Firefox, clicking the input field does not enable typing.

I discovered this issue after not using the site for a bit. I think an update to the generator within the past few months may have introduced this problem.

Beautiful website, by the way. Thank you for all your hard work!

**Comment by frederickobrien** [comment]
Fixed! Thanks for raising this, I made some changes to the generator page a couple of weeks ago and this slipped through
